# Generated by Django 4.0.3 on 2023-03-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='season',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
